### ISSUE TITLE
Mkdir fails

### ISSUE THREAD

**Issue by HadiSDev** [johnny-mh/devlog#12]
Hi

I keep getting this error after adding the fuse() component to my astro config:
```
 error   EINVAL: invalid argument, mkdir '\C:\Users\<USER_NAME>\WebstormProjects\<PROJECT_NAME>\dist'
  File:
    C:\Users\<USER_NAME>\WebstormProjects\<PROJECT_NAME>\node_modules\astro-fuse\dist\chunk-PRXD3I6Q.mjs:255:5
  Code:
    254 |   if (!existsSync3(outDir)) {
    > 255 |     mkdirSync2(dirname2(outputPath));
          |     ^
      256 |     writeFileSync2(outputPath, "{}");
      257 |   }
      258 |   const result = /* @__PURE__ */ new Map();

```

Any ideas?

**Comment by sbkbdigital** [comment]
Hi @HadiSDev. I get this error:

`EINVAL: invalid argument, mkdir 'C:\C:\test\dist'
  Stack trace:
    at mkdirSync (node:fs:1382:26)
    at astro:build:done (file:///C:/test/node_modules/astro-fuse/dist/chunk-PRXD3I6Q.mjs:244:9)
    at async AstroBuilder.build (file:///C:/test/node_modules/astro/dist/core/build/index.js:147:5)
    at async build (file:///C:/test/node_modules/astro/dist/core/build/index.js:45:3)
    at async runCommand (file:///C:/test/node_modules/astro/dist/cli/index.js:124:7)`

**Comment by wtto00** [comment]
Hi, I got the same error. Any update on this?

**Comment by johnny-mh** [comment]
The difference in the directory creation paths between @HadiSDev and @sbkbdigital is a bit confusing to me.

Also I found an issue seems to be related @sbkbdigital's case. https://github.com/modelcontextprotocol/servers/issues/699

`astro-fuse` get outDir from [`outDir` from astrojs configuration.](https://docs.astro.build/en/reference/configuration-reference/#outdir) where the default value is `./dist`.

I wrote a simplified example to reproduce the issue:

```ts
// test.mjs
import {mkdirSync} from 'node:fs'
import {dirname, join} from 'node:path'

const outputPath = join('./dist', 'fuse.json')
mkdirSync(dirname(outputPath)) // 😕 This line throw errors
```

I'd appreciate any help resolving this. If you're experiencing the same issue, please leave a comment on the issue.

Thanks!

**Comment by johnny-mh** [comment]
also thanks to @wtto00

**Comment by HadiSDev** [comment]
> also thanks to @wtto00 

I forgot about this 😅🤣
